services:
  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    networks:
      - observability
    restart: unless-stopped
  
  loki:
    image: grafana/loki:3.6.6
    container_name: loki
    user: root
    command:
      - '-config.file=/etc/loki/loki.yaml'
      - '-target=all'
    volumes:
      - ./loki-config.yaml:/etc/loki/loki.yaml:ro
      - loki-data:/loki
      - loki-wal:/wal
    ports:
      - '3100:3100'
    networks:
      - observability
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  services:
    tempo:
      image: grafana/tempo:2.10.1
      container_name: tempo
      command:
        - '-config.file=/etc/tempo/tempo.yaml'
        - '-target=all'
      volumes:
        - ./tempo-config.yaml:/etc/tempo/tempo.yaml:ro
        - tempo-data:/var/tempo
      ports:
        - '3200:3200'
      networks:
        - observability
      restart: unless-stopped

volumes:
  prometheus_data:
  loki-data:
  loki-wal:
  tempo-data: